<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/animate.css" rel="stylesheet">
<link href="css/bootsnav.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/font-awesome.min.css" rel="stylesheet">
<link href="css/utility-classes.css" rel="stylesheet">
<link href="css/margin-padding.css" rel="stylesheet">
<link href="css/lightbox.min.css" rel="stylesheet">
<link href="css/normalize.css" rel="stylesheet">
<link href="css/style-main.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">